# Generated by Django 5.2.17 on 2026-10-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('name_key', models.CharField(max_length=60, unique=True)),
                ('master_salt', models.CharField(max_length=64)),
                ('master_wrapped', models.TextField()),
                ('recovery_question', models.CharField(max_length=255)),
                ('recovery_salt', models.CharField(max_length=64)),
                ('recovery_wrapped', models.TextField()),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('login_failed', models.PositiveSmallIntegerField(default=0)),
                ('login_locked_until', models.DateTimeField(blank=True, null=True)),
                ('recovery_failed', models.PositiveSmallIntegerField(default=0)),
                ('recovery_locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('encoded_password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='password.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]